### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by codito** [codito/habito#10]
In the `strict` mode habito will help users (tracking impulsive habits) to keep discipline. Here's how the operations will behave:
- Configuration
  This mode will be configurable via a `rc` file or inbuilt command. Once strict mode is enabled, user can only schedule a turn off of the mode. E.g. habito config strict=false will take effect after a week.
- Edit
  User can edit `name` of the habit right away. Edits to `quanta` can be scheduled again. For a new habit, habito will allow unscheduled modifications until first `7` check-ins are done.
- Delete
  User can only schedule deletes or archive operations. For a new habit, habito will allow unscheduled modifications until first `7` check-ins are done.
- Check-in
  Check-in for the day will continue to work as expected. Past check-ins will have a threshold, e.g. 1 past check-in/3 days for a daily goal. Usually one allowance per 3 \* period of habit update.

This feature request is related to discussions in #7 and #4.

**Comment by Ben-Baert** [comment]
I like the de-facto trial period idea, where you can try things out and get them right before committing to them. It also deals with typos or adding a todo to try out the program. Definitely a good idea.

If I understand this correctly, strict mode will be optional? In other words, the default behaviour would still be to allow all actions at any time? Would strict mode be global or on a per habit basis? Maybe it's possible to set a default in an rc/config file, but deviate on a per-habit basis.

As for edits to the quanta, I think this relates heavily to #9. Edits to quanta that are planned should be outside the scope of the strict mode.

**Comment by codito** [comment]
Yes, I'm thinking `strict` mode may be optional. Per habit mode is probably better. In case strict mode is enabled, manual edits to quanta can be only scheduled (either user finds a quanta too much and wants to relax or she wants to increase it).

Automated edits to quanta are out of scope for this feature. Let's discuss that in scope of #9.

**Comment by codito** [comment]
Closing this issue as *won't fix*, we will reconsider if there is enough interest for a feature like this.
