### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by Ben-Baert** [codito/habito#11]
I'm currently refactoring the code. A number of thoughts regarding the models:
- I think the `Model` in `HabitModel` and `ActivityModel` can be omitted, since the fact that it starts with a capital letter already indicates that it is one by convention. On top of this, since the models would be in their own module, this would be even more repetitive (`models.HabitModel` vs `models.Habit`).
- I'm not sure whether `Activity` is semantically the best term for what it represents. I think `Log` is more appropriate, because a checkin doesn't always directly map to an activity, for instance in the example you gave in #9 (nr of meetings/week). It often does, but not necessarily.

These are some of the issues directly relating to the refactoring, that is, making the code cleaner without adding more features. There are of course other proposals relating to the models, such as #9, but I won't deal with those just yet.

**Comment by codito** [comment]
Agree with these thoughts.

**Comment by codito** [comment]
Models are already a separate module. We've dropped `Model` from the table names, migrations are in place for next version. Closing this issue.
