### ISSUE TITLE
Feature request - Ability to checkin a habit for a past date

### ISSUE THREAD

**Issue by andrewpdawes** [codito/habito#31]
Hi 

It would be great to be able to add a checkin for a habit on a past date.

For example: "habito checkin Read Book -q 1 24/05/23" 

This would be useful if, for some reason, you were unable to enter checkins on a particular day.

Thanks for the great work. Really enjoying using the programme.

Cheers

Andy

**Comment by codito** [comment]
@andrewpdawes thank you for the feature request, will add this.

**Comment by codito** [comment]
@andrewpdawes which version of Habito are you using?

In the latest 1.1.x version, you should be able to use `habito checkin Read book -q 1 -d 05/24` (-d takes date in mm/dd format)

**Comment by andrewpdawes** [comment]
@codito 

I checked and am running the 1.1 version. I tried your suggestion above. It works perfectly. Appreciate you looking into it. Really helpful software.

Cheers

Andy
