### ISSUE TITLE
Why an ActivityModel entry per checkin rather than per day?

### ISSUE THREAD

**Issue by Ben-Baert** [codito/habito#6]
An ActivtyModel entry is added per checkin. If you checkin multiple times per day, multiple entries are added. However, in the list, we just sum the different quanta together. Wouldn't it be easier to make one ActivityModel entry per day where we update the quanta per checkin? Or did you design this with a future feature in mind?

**Comment by codito** [comment]
Yes, it will be easier to have one entry per day.

The idea is little futuristic. May be we can use this activity data to create a rhythm in using `habito` itself. Some kind of gamification, e.g. we could notify the user at the most frequently update time to checkin for a habit, or just try to predict when he will do the next checkin for fun.

This checkin metadata could definitely go into another model, we can reduce overhead to try to compute habit activities during table rendering.

**Comment by codito** [comment]
Check-in metadata like `target` is added to a `Summary` model now. Will keep activity as one row per check-in for now.
