### ISSUE TITLE
Disambiguate user input

### ISSUE THREAD

**Issue by codito** [codito/habito#8]
There's a possibility of ambiguity with names in `habito checkin`. We should fix that with some kind of interactive input (may be with [inquirer](http://python-inquirer.readthedocs.io/en/latest/) or [qprompt](http://qprompt.readthedocs.io/en/latest)).

Allow user to pick a habit, something like (see proposal in #5 from @Ben-Baert):

```
your input matches multiple items:
1. item one
2. item two

Which one do you mean (type in the number to continue)?
```

**Comment by Ben-Baert** [comment]
I can build this next week (perhaps after the refactoring, which I think is the highest priority right now, see #3). It could be similar to [this code I wrote](https://github.com/Ben-Baert/irail-cli/blob/master/irail/commands/utils.py#L157-181). This could go in the utils file and all commands that need it can access it this way.

**Comment by codito** [comment]
No rush for implementing :) I agree refactoring is the highest priority.

**Comment by Ben-Baert** [comment]
Really sorry for the delay -- work and exams got a bit in the way. 

The refactoring is done but getting the tests to work is proving to be a bit (a lot, actually :)) of a pain. I hope to finish them within a couple of days.

Again, my apologies!

**Comment by codito** [comment]
No problem, Ben. If you have a branch, I will be happy to share the pain :)
